version: '3.8'

services:
  db:
    image: mysql:8
    container_name: proplayas_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proplayas
      MYSQL_USER: proplayas_user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -proot --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 512M

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: proplayas_php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "php -v >/dev/null 2>&1 && (php -r 'exit(extension_loaded(\"pdo_mysql\")?0:1);')"]
      interval: 15s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  webserver:
    image: nginx:alpine
    container_name: proplayas_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./src/public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      app:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M

  mailhog:
    image: mailhog/mailhog
    container_name: proplayas_mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db_data:
