version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: proplayas_php
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: proplayas_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./src/public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: proplayas_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proplayas
      MYSQL_USER: proplayas_user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: proplayas_mailhog
    ports:
      - "8025:8025" # Interfaz web para visualizar correos
      - "1025:1025" # Puerto SMTP


volumes: 
    db_data:

